global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nifi'
    scheme: https
    metrics_path: /nifi-api/flow/metrics/prometheus
    static_configs:
      - targets: ['localhost:8443']
    tls_config:
      insecure_skip_verify: true
    authorization:
      type: Bearer
      credentials: "eyJraWQiOiJhYjBlMWE2MS00YjM5LTRkYWMtODFhNi0wY2UyNzczMTA3M2YiLCJhbGciOiJFZERTQSJ9.eyJzdWIiOiI1ZTBlYjRiMS01ZDY1LTQ5NWUtOTEyNC04OTlmN2Y4NmQ3N2YiLCJhdWQiOiJodHRwczovLzAuMC4wLjA6ODQ0MyIsIm5iZiI6MTc2MjgwODE2OCwiaXNzIjoiaHR0cHM6Ly8wLjAuMC4wOjg0NDMiLCJncm91cHMiOltdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiI1ZTBlYjRiMS01ZDY1LTQ5NWUtOTEyNC04OTlmN2Y4NmQ3N2YiLCJleHAiOjE3NjI4MzY5NjgsImlhdCI6MTc2MjgwODE2OCwianRpIjoiYzZkMDk2NGQtOTBlZi00NDViLWI3NmUtNzQzZTQwMTgzNGFkIn0.uzlCjzt7D6W649_fZgssBy7wYnuQ1GPTNft-PWuBKvKnkm7OvakJjTrujoy5d5JnMiVxrWtZ8Rmzy4du4AuoAA"
