global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nifi'
    scheme: https
    metrics_path: /nifi-api/flow/metrics/prometheus
    static_configs:
      - targets: ['localhost:8443']
    tls_config:
      insecure_skip_verify: true
    authorization:
      type: Bearer
      credentials: "eyJraWQiOiI1NTYyMjc2NS00YzBlLTRhNTktYTRjMS04NzEzZjQzMmM1ZTciLCJhbGciOiJFZERTQSJ9.eyJzdWIiOiJhZjc4ODQwMC05MGZiLTRlM2QtOWE0Yi1iMWM0ZDgxZjY2MjEiLCJhdWQiOiJodHRwczovLzAuMC4wLjA6ODQ0MyIsIm5iZiI6MTc2Mjg4NzcxOSwiaXNzIjoiaHR0cHM6Ly8wLjAuMC4wOjg0NDMiLCJncm91cHMiOltdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZjc4ODQwMC05MGZiLTRlM2QtOWE0Yi1iMWM0ZDgxZjY2MjEiLCJleHAiOjE3NjI5MTY1MTksImlhdCI6MTc2Mjg4NzcxOSwianRpIjoiNTY2MDAwNGItMjU2MS00NThkLWE0YjItOTEwMTc1MjkwZWZjIn0.68P0hL6YAsIrqgh0CwgWXEsfhtMRYAkQTYPQiMEopCtk87yEe6myp83c7VtQX8tySwPj979FLqQ7xMoan4P3Dw"
  
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'statsd'
    static_configs:
      - targets: ['statsd-exporter:9102']