global:
  scrape_interval: 15s

scrape_configs:
  # Scrape node exporter (CPU, RAM, disk, dll)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape Airflow via statsd-exporter
  - job_name: 'airflow'
    static_configs:
      - targets: ['statsd-exporter:9102']
